# This is a basic workflow to help you get started with Actions

name: MPK

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        name: 构建MPK 和 DEMO项目
        permissions: write-all
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - name: Get package info
              id: package
              uses: codex-team/action-nodejs-package-info@v1
            - name: Install Dependencies
              run: |
                  npm ci
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
            - name: unit testing
              run: |
                  npm test
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
            - name: npm run release
              run: |
                  git clone https://github.com/engalar/mendix-testproject-960.git --depth=1 ./tests/testProject
                  rm -rf tests/testProject/.git
                  cp -r dummy/* tests/testProject/
                  npm run release
                  cp -r dist/${{ steps.package.outputs.version }}/* tests/testProject/widgets/
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
            - name: "Zip testProject"
              run: |
                  pushd tests/testProject/
                  zip -r ../../dist/demo.zip *
                  popd
            - name: "Release MPK Files"
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "${{ steps.package.outputs.name }}-v${{ steps.package.outputs.version }}"
                  prerelease: false
                  title: "${{ steps.package.outputs.widgetName }}"
                  files: |
                      dist/**/*.mpk
                      dist/demo.zip
